# Generated by Django 5.2.1 on 2025-05-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="intro",
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=models.TextField(max_length=13),
        ),
    ]
