# Generated by Django 5.2.1 on 2025-05-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_profile_intro_alter_profile_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="followings",
            field=models.ManyToManyField(
                related_name="followers", to="accounts.profile"
            ),
        ),
    ]
