# Generated by Django 5.2.1 on 2025-05-20 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="blog",
            new_name="post",
        ),
    ]
